DROP DATABASE IF EXISTS devQA_CM;
CREATE DATABASE devQA_CM;
USE devQA_CM;

CREATE TABLE question(
    id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `subject` VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    create_date DATETIME NOT NULL
);